apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-game.backend.fullname" . }}
  labels:
    {{- include "k8s-game.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-game.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-game.backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-game.serviceAccountName" . }}
      containers:
        - name: backend
          image: {{ include "k8s-game.backend.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "k8s-game.backend.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
