apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-game.backend.fullname" . }}
  labels:
    {{- include "k8s-game.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-game.backend.selectorLabels" . | nindent 4 }}
